//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.09 at 09:53:03 AM CET 
//


package es.tid.neosdp.bluevia.schemas.mms.v2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.tid.neosdp.bluevia.schemas.mms.v2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MmsOutboundRequest_QNAME = new QName("http://api.bluevia.com/schemas/v2/mms", "mmsOutboundRequest");
    private final static QName _MmsInboundList_QNAME = new QName("http://api.bluevia.com/schemas/v2/mms", "mmsInboundList");
    private final static QName _MmsOutbound_QNAME = new QName("http://api.bluevia.com/schemas/v2/mms", "mmsOutbound");
    private final static QName _DeliveryStatus_QNAME = new QName("http://api.bluevia.com/schemas/v2/mms", "deliveryStatus");
    private final static QName _MmsOutboundList_QNAME = new QName("http://api.bluevia.com/schemas/v2/mms", "mmsOutboundList");
    private final static QName _Exception_QNAME = new QName("http://api.bluevia.com/schemas/v2/common", "exception");
    private final static QName _MmsInbound_QNAME = new QName("http://api.bluevia.com/schemas/v2/mms", "mmsInbound");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.tid.neosdp.bluevia.schemas.mms.v2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MmsInboundListType }
     * 
     */
    public MmsInboundListType createMmsInboundListType() {
        return new MmsInboundListType();
    }

    /**
     * Create an instance of {@link MmsOutboundRequestType }
     * 
     */
    public MmsOutboundRequestType createMmsOutboundRequestType() {
        return new MmsOutboundRequestType();
    }

    /**
     * Create an instance of {@link DestinationsInfoType }
     * 
     */
    public DestinationsInfoType createDestinationsInfoType() {
        return new DestinationsInfoType();
    }

    /**
     * Create an instance of {@link NameValuePairType }
     * 
     */
    public NameValuePairType createNameValuePairType() {
        return new NameValuePairType();
    }

    /**
     * Create an instance of {@link MmsOutboundListType }
     * 
     */
    public MmsOutboundListType createMmsOutboundListType() {
        return new MmsOutboundListType();
    }

    /**
     * Create an instance of {@link MmsInboundType }
     * 
     */
    public MmsInboundType createMmsInboundType() {
        return new MmsInboundType();
    }

    /**
     * Create an instance of {@link DeliveryStatusNotificationType }
     * 
     */
    public DeliveryStatusNotificationType createDeliveryStatusNotificationType() {
        return new DeliveryStatusNotificationType();
    }

    /**
     * Create an instance of {@link ExceptionType }
     * 
     */
    public ExceptionType createExceptionType() {
        return new ExceptionType();
    }

    /**
     * Create an instance of {@link MmsOutboundType }
     * 
     */
    public MmsOutboundType createMmsOutboundType() {
        return new MmsOutboundType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MmsOutboundRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.bluevia.com/schemas/v2/mms", name = "mmsOutboundRequest")
    public JAXBElement<MmsOutboundRequestType> createMmsOutboundRequest(MmsOutboundRequestType value) {
        return new JAXBElement<MmsOutboundRequestType>(_MmsOutboundRequest_QNAME, MmsOutboundRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MmsInboundListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.bluevia.com/schemas/v2/mms", name = "mmsInboundList")
    public JAXBElement<MmsInboundListType> createMmsInboundList(MmsInboundListType value) {
        return new JAXBElement<MmsInboundListType>(_MmsInboundList_QNAME, MmsInboundListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MmsOutboundType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.bluevia.com/schemas/v2/mms", name = "mmsOutbound")
    public JAXBElement<MmsOutboundType> createMmsOutbound(MmsOutboundType value) {
        return new JAXBElement<MmsOutboundType>(_MmsOutbound_QNAME, MmsOutboundType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeliveryStatusNotificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.bluevia.com/schemas/v2/mms", name = "deliveryStatus")
    public JAXBElement<DeliveryStatusNotificationType> createDeliveryStatus(DeliveryStatusNotificationType value) {
        return new JAXBElement<DeliveryStatusNotificationType>(_DeliveryStatus_QNAME, DeliveryStatusNotificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MmsOutboundListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.bluevia.com/schemas/v2/mms", name = "mmsOutboundList")
    public JAXBElement<MmsOutboundListType> createMmsOutboundList(MmsOutboundListType value) {
        return new JAXBElement<MmsOutboundListType>(_MmsOutboundList_QNAME, MmsOutboundListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExceptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.bluevia.com/schemas/v2/common", name = "exception")
    public JAXBElement<ExceptionType> createException(ExceptionType value) {
        return new JAXBElement<ExceptionType>(_Exception_QNAME, ExceptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MmsInboundType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.bluevia.com/schemas/v2/mms", name = "mmsInbound")
    public JAXBElement<MmsInboundType> createMmsInbound(MmsInboundType value) {
        return new JAXBElement<MmsInboundType>(_MmsInbound_QNAME, MmsInboundType.class, null, value);
    }

}
