//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.09 at 05:39:53 PM CEST 
//


package es.tid.neosdp.bluevia.schemas.payments.v2;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RefundRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RefundRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *             &lt;sequence minOccurs="0">
 *               &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *               &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *             &lt;/sequence>
 *             &lt;element name="transactionIdToRefund" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *             &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *             &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *             &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element name="referenceCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RefundRequestType", propOrder = {
    "content"
})
public class RefundRequestType {

    @XmlElementRefs({
        @XmlElementRef(name = "userId", namespace = "http://api.bluevia.com/schemas/v2/payment", type = JAXBElement.class),
        @XmlElementRef(name = "description", namespace = "http://api.bluevia.com/schemas/v2/payment", type = JAXBElement.class),
        @XmlElementRef(name = "currency", namespace = "http://api.bluevia.com/schemas/v2/payment", type = JAXBElement.class),
        @XmlElementRef(name = "amount", namespace = "http://api.bluevia.com/schemas/v2/payment", type = JAXBElement.class),
        @XmlElementRef(name = "transactionIdToRefund", namespace = "http://api.bluevia.com/schemas/v2/payment", type = JAXBElement.class),
        @XmlElementRef(name = "referenceCode", namespace = "http://api.bluevia.com/schemas/v2/payment", type = JAXBElement.class)
    })
    protected List<JAXBElement<? extends Serializable>> content;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "Description" is used by two different parts of a schema. See: 
     * line 116 of file:/D:/java/eclipse_indigo_workspace/JAXBschemas/resources/xsd/api.bluevia.com_payments_v2_0.xsd
     * line 107 of file:/D:/java/eclipse_indigo_workspace/JAXBschemas/resources/xsd/api.bluevia.com_payments_v2_0.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends Serializable>> getContent() {
        if (content == null) {
            content = new ArrayList<JAXBElement<? extends Serializable>>();
        }
        return this.content;
    }

}
