//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.09 at 09:51:54 AM CET 
//


package es.tid.neosdp.bluevia.schemas.sms.v2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.tid.neosdp.bluevia.schemas.sms.v2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DeliveryStatus_QNAME = new QName("http://api.bluevia.com/schemas/v2/sms", "deliveryStatus");
    private final static QName _SmsInboundList_QNAME = new QName("http://api.bluevia.com/schemas/v2/sms", "smsInboundList");
    private final static QName _SmsOutbound_QNAME = new QName("http://api.bluevia.com/schemas/v2/sms", "smsOutbound");
    private final static QName _SmsInbound_QNAME = new QName("http://api.bluevia.com/schemas/v2/sms", "smsInbound");
    private final static QName _Exception_QNAME = new QName("http://api.bluevia.com/schemas/v2/common", "exception");
    private final static QName _SmsOutboundList_QNAME = new QName("http://api.bluevia.com/schemas/v2/sms", "smsOutboundList");
    private final static QName _SmsOutboundRequest_QNAME = new QName("http://api.bluevia.com/schemas/v2/sms", "smsOutboundRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.tid.neosdp.bluevia.schemas.sms.v2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExceptionType }
     * 
     */
    public ExceptionType createExceptionType() {
        return new ExceptionType();
    }

    /**
     * Create an instance of {@link SmsOutboundRequestType }
     * 
     */
    public SmsOutboundRequestType createSmsOutboundRequestType() {
        return new SmsOutboundRequestType();
    }

    /**
     * Create an instance of {@link DeliveryStatusNotificationType }
     * 
     */
    public DeliveryStatusNotificationType createDeliveryStatusNotificationType() {
        return new DeliveryStatusNotificationType();
    }

    /**
     * Create an instance of {@link SmsInboundType }
     * 
     */
    public SmsInboundType createSmsInboundType() {
        return new SmsInboundType();
    }

    /**
     * Create an instance of {@link DestinationsInfoType }
     * 
     */
    public DestinationsInfoType createDestinationsInfoType() {
        return new DestinationsInfoType();
    }

    /**
     * Create an instance of {@link SmsInboundListType }
     * 
     */
    public SmsInboundListType createSmsInboundListType() {
        return new SmsInboundListType();
    }

    /**
     * Create an instance of {@link SmsOutboundType }
     * 
     */
    public SmsOutboundType createSmsOutboundType() {
        return new SmsOutboundType();
    }

    /**
     * Create an instance of {@link NameValuePairType }
     * 
     */
    public NameValuePairType createNameValuePairType() {
        return new NameValuePairType();
    }

    /**
     * Create an instance of {@link SmsOutboundListType }
     * 
     */
    public SmsOutboundListType createSmsOutboundListType() {
        return new SmsOutboundListType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeliveryStatusNotificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.bluevia.com/schemas/v2/sms", name = "deliveryStatus")
    public JAXBElement<DeliveryStatusNotificationType> createDeliveryStatus(DeliveryStatusNotificationType value) {
        return new JAXBElement<DeliveryStatusNotificationType>(_DeliveryStatus_QNAME, DeliveryStatusNotificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SmsInboundListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.bluevia.com/schemas/v2/sms", name = "smsInboundList")
    public JAXBElement<SmsInboundListType> createSmsInboundList(SmsInboundListType value) {
        return new JAXBElement<SmsInboundListType>(_SmsInboundList_QNAME, SmsInboundListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SmsOutboundType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.bluevia.com/schemas/v2/sms", name = "smsOutbound")
    public JAXBElement<SmsOutboundType> createSmsOutbound(SmsOutboundType value) {
        return new JAXBElement<SmsOutboundType>(_SmsOutbound_QNAME, SmsOutboundType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SmsInboundType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.bluevia.com/schemas/v2/sms", name = "smsInbound")
    public JAXBElement<SmsInboundType> createSmsInbound(SmsInboundType value) {
        return new JAXBElement<SmsInboundType>(_SmsInbound_QNAME, SmsInboundType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExceptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.bluevia.com/schemas/v2/common", name = "exception")
    public JAXBElement<ExceptionType> createException(ExceptionType value) {
        return new JAXBElement<ExceptionType>(_Exception_QNAME, ExceptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SmsOutboundListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.bluevia.com/schemas/v2/sms", name = "smsOutboundList")
    public JAXBElement<SmsOutboundListType> createSmsOutboundList(SmsOutboundListType value) {
        return new JAXBElement<SmsOutboundListType>(_SmsOutboundList_QNAME, SmsOutboundListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SmsOutboundRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.bluevia.com/schemas/v2/sms", name = "smsOutboundRequest")
    public JAXBElement<SmsOutboundRequestType> createSmsOutboundRequest(SmsOutboundRequestType value) {
        return new JAXBElement<SmsOutboundRequestType>(_SmsOutboundRequest_QNAME, SmsOutboundRequestType.class, null, value);
    }

}
