//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 08:40:35 AM CEST 
//


package com.telefonica.schemas.unica.soap.charging.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AcquiredPurchaseModelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AcquiredPurchaseModelType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="purchaseCode" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}PurchaseCodeType"/>
 *         &lt;element name="subPurchaseCode" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}SubPurchaseCodeType" minOccurs="0"/>
 *         &lt;element name="description" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}DescriptionType"/>
 *         &lt;element name="validityStartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="validityEndType" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="validityUnits" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="validityEndDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="thresholdInformation" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}ThresholdInformationType" minOccurs="0"/>
 *         &lt;element name="renewalInformation" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}RenewalInformationAcquiredType" minOccurs="0"/>
 *         &lt;element name="otherEvents" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}EventsListType" minOccurs="0"/>
 *         &lt;element name="purchaseModelInfo" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}PurchaseModelType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AcquiredPurchaseModelType", propOrder = {
    "purchaseCode",
    "subPurchaseCode",
    "description",
    "validityStartDate",
    "validityEndType",
    "validityUnits",
    "validityEndDate",
    "thresholdInformation",
    "renewalInformation",
    "otherEvents",
    "purchaseModelInfo"
})
public class AcquiredPurchaseModelType {

    protected int purchaseCode;
    protected Integer subPurchaseCode;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar validityStartDate;
    protected int validityEndType;
    protected Integer validityUnits;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar validityEndDate;
    protected ThresholdInformationType thresholdInformation;
    protected RenewalInformationAcquiredType renewalInformation;
    protected EventsListType otherEvents;
    @XmlElement(required = true)
    protected PurchaseModelType purchaseModelInfo;

    /**
     * Gets the value of the purchaseCode property.
     * 
     */
    public int getPurchaseCode() {
        return purchaseCode;
    }

    /**
     * Sets the value of the purchaseCode property.
     * 
     */
    public void setPurchaseCode(int value) {
        this.purchaseCode = value;
    }

    /**
     * Gets the value of the subPurchaseCode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSubPurchaseCode() {
        return subPurchaseCode;
    }

    /**
     * Sets the value of the subPurchaseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSubPurchaseCode(Integer value) {
        this.subPurchaseCode = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the validityStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidityStartDate() {
        return validityStartDate;
    }

    /**
     * Sets the value of the validityStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidityStartDate(XMLGregorianCalendar value) {
        this.validityStartDate = value;
    }

    /**
     * Gets the value of the validityEndType property.
     * 
     */
    public int getValidityEndType() {
        return validityEndType;
    }

    /**
     * Sets the value of the validityEndType property.
     * 
     */
    public void setValidityEndType(int value) {
        this.validityEndType = value;
    }

    /**
     * Gets the value of the validityUnits property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getValidityUnits() {
        return validityUnits;
    }

    /**
     * Sets the value of the validityUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setValidityUnits(Integer value) {
        this.validityUnits = value;
    }

    /**
     * Gets the value of the validityEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidityEndDate() {
        return validityEndDate;
    }

    /**
     * Sets the value of the validityEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidityEndDate(XMLGregorianCalendar value) {
        this.validityEndDate = value;
    }

    /**
     * Gets the value of the thresholdInformation property.
     * 
     * @return
     *     possible object is
     *     {@link ThresholdInformationType }
     *     
     */
    public ThresholdInformationType getThresholdInformation() {
        return thresholdInformation;
    }

    /**
     * Sets the value of the thresholdInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ThresholdInformationType }
     *     
     */
    public void setThresholdInformation(ThresholdInformationType value) {
        this.thresholdInformation = value;
    }

    /**
     * Gets the value of the renewalInformation property.
     * 
     * @return
     *     possible object is
     *     {@link RenewalInformationAcquiredType }
     *     
     */
    public RenewalInformationAcquiredType getRenewalInformation() {
        return renewalInformation;
    }

    /**
     * Sets the value of the renewalInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link RenewalInformationAcquiredType }
     *     
     */
    public void setRenewalInformation(RenewalInformationAcquiredType value) {
        this.renewalInformation = value;
    }

    /**
     * Gets the value of the otherEvents property.
     * 
     * @return
     *     possible object is
     *     {@link EventsListType }
     *     
     */
    public EventsListType getOtherEvents() {
        return otherEvents;
    }

    /**
     * Sets the value of the otherEvents property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventsListType }
     *     
     */
    public void setOtherEvents(EventsListType value) {
        this.otherEvents = value;
    }

    /**
     * Gets the value of the purchaseModelInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PurchaseModelType }
     *     
     */
    public PurchaseModelType getPurchaseModelInfo() {
        return purchaseModelInfo;
    }

    /**
     * Sets the value of the purchaseModelInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PurchaseModelType }
     *     
     */
    public void setPurchaseModelInfo(PurchaseModelType value) {
        this.purchaseModelInfo = value;
    }

}
