//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.09 at 09:17:46 AM CEST 
//


package com.telefonica.schemas.unica.soap.charging.v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="plans" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}ArrayOfPlanDefinitionType"/>
 *         &lt;element name="registerPlan" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}RegisterPlanType"/>
 *         &lt;element name="topUpPlan" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}TopUpPlanType"/>
 *         &lt;element name="updatePlanTopUpSettings" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}UpdatePlanTopUpSettingsType"/>
 *         &lt;element name="freeTopUp" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}FreeTopUpType"/>
 *         &lt;element name="planRegistrationId">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="guidType" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}guidType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "plans",
    "registerPlan",
    "topUpPlan",
    "updatePlanTopUpSettings",
    "freeTopUp",
    "planRegistrationId"
})
@XmlRootElement(name = "additionalCallControlInfo")
public class AdditionalCallControlInfo {

    @XmlElementRef(name = "plans", namespace = "http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1", type = JAXBElement.class)
    protected JAXBElement<ArrayOfPlanDefinitionType> plans;
    @XmlElementRef(name = "registerPlan", namespace = "http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1", type = JAXBElement.class)
    protected JAXBElement<RegisterPlanType> registerPlan;
    @XmlElementRef(name = "topUpPlan", namespace = "http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1", type = JAXBElement.class)
    protected JAXBElement<TopUpPlanType> topUpPlan;
    @XmlElementRef(name = "updatePlanTopUpSettings", namespace = "http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1", type = JAXBElement.class)
    protected JAXBElement<UpdatePlanTopUpSettingsType> updatePlanTopUpSettings;
    @XmlElementRef(name = "freeTopUp", namespace = "http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1", type = JAXBElement.class)
    protected JAXBElement<FreeTopUpType> freeTopUp;
    protected AdditionalCallControlInfo.PlanRegistrationId planRegistrationId;

    /**
     * Gets the value of the plans property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfPlanDefinitionType }{@code >}
     *     
     */
    public JAXBElement<ArrayOfPlanDefinitionType> getPlans() {
        return plans;
    }

    /**
     * Sets the value of the plans property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfPlanDefinitionType }{@code >}
     *     
     */
    public void setPlans(JAXBElement<ArrayOfPlanDefinitionType> value) {
        this.plans = ((JAXBElement<ArrayOfPlanDefinitionType> ) value);
    }

    /**
     * Gets the value of the registerPlan property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link RegisterPlanType }{@code >}
     *     
     */
    public JAXBElement<RegisterPlanType> getRegisterPlan() {
        return registerPlan;
    }

    /**
     * Sets the value of the registerPlan property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link RegisterPlanType }{@code >}
     *     
     */
    public void setRegisterPlan(JAXBElement<RegisterPlanType> value) {
        this.registerPlan = ((JAXBElement<RegisterPlanType> ) value);
    }

    /**
     * Gets the value of the topUpPlan property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TopUpPlanType }{@code >}
     *     
     */
    public JAXBElement<TopUpPlanType> getTopUpPlan() {
        return topUpPlan;
    }

    /**
     * Sets the value of the topUpPlan property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TopUpPlanType }{@code >}
     *     
     */
    public void setTopUpPlan(JAXBElement<TopUpPlanType> value) {
        this.topUpPlan = ((JAXBElement<TopUpPlanType> ) value);
    }

    /**
     * Gets the value of the updatePlanTopUpSettings property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link UpdatePlanTopUpSettingsType }{@code >}
     *     
     */
    public JAXBElement<UpdatePlanTopUpSettingsType> getUpdatePlanTopUpSettings() {
        return updatePlanTopUpSettings;
    }

    /**
     * Sets the value of the updatePlanTopUpSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link UpdatePlanTopUpSettingsType }{@code >}
     *     
     */
    public void setUpdatePlanTopUpSettings(JAXBElement<UpdatePlanTopUpSettingsType> value) {
        this.updatePlanTopUpSettings = ((JAXBElement<UpdatePlanTopUpSettingsType> ) value);
    }

    /**
     * Gets the value of the freeTopUp property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link FreeTopUpType }{@code >}
     *     
     */
    public JAXBElement<FreeTopUpType> getFreeTopUp() {
        return freeTopUp;
    }

    /**
     * Sets the value of the freeTopUp property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link FreeTopUpType }{@code >}
     *     
     */
    public void setFreeTopUp(JAXBElement<FreeTopUpType> value) {
        this.freeTopUp = ((JAXBElement<FreeTopUpType> ) value);
    }

    /**
     * Gets the value of the planRegistrationId property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalCallControlInfo.PlanRegistrationId }
     *     
     */
    public AdditionalCallControlInfo.PlanRegistrationId getPlanRegistrationId() {
        return planRegistrationId;
    }

    /**
     * Sets the value of the planRegistrationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalCallControlInfo.PlanRegistrationId }
     *     
     */
    public void setPlanRegistrationId(AdditionalCallControlInfo.PlanRegistrationId value) {
        this.planRegistrationId = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="guidType" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}guidType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "guidType"
    })
    public static class PlanRegistrationId {

        @XmlElement(required = true, nillable = true)
        protected String guidType;

        /**
         * Gets the value of the guidType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGuidType() {
            return guidType;
        }

        /**
         * Sets the value of the guidType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGuidType(String value) {
            this.guidType = value;
        }

    }

}
