//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.09 at 09:17:46 AM CEST 
//


package com.telefonica.schemas.unica.soap.charging.v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;


/**
 * <p>Java class for CallbackServiceLimitsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CallbackServiceLimitsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MaxCallDuration" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}duration" minOccurs="0"/>
 *         &lt;element name="MaxWhitelistDestinations" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CallbackServiceLimitsType", propOrder = {
    "maxCallDuration",
    "maxWhitelistDestinations"
})
public class CallbackServiceLimitsType {

    @XmlElementRef(name = "MaxCallDuration", namespace = "http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1", type = JAXBElement.class)
    protected JAXBElement<Duration> maxCallDuration;
    @XmlElementRef(name = "MaxWhitelistDestinations", namespace = "http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1", type = JAXBElement.class)
    protected JAXBElement<Integer> maxWhitelistDestinations;

    /**
     * Gets the value of the maxCallDuration property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Duration }{@code >}
     *     
     */
    public JAXBElement<Duration> getMaxCallDuration() {
        return maxCallDuration;
    }

    /**
     * Sets the value of the maxCallDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Duration }{@code >}
     *     
     */
    public void setMaxCallDuration(JAXBElement<Duration> value) {
        this.maxCallDuration = ((JAXBElement<Duration> ) value);
    }

    /**
     * Gets the value of the maxWhitelistDestinations property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getMaxWhitelistDestinations() {
        return maxWhitelistDestinations;
    }

    /**
     * Sets the value of the maxWhitelistDestinations property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setMaxWhitelistDestinations(JAXBElement<Integer> value) {
        this.maxWhitelistDestinations = ((JAXBElement<Integer> ) value);
    }

}
