//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 08:40:35 AM CEST 
//


package com.telefonica.schemas.unica.soap.charging.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PurchaseModelUsageTariffType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PurchaseModelUsageTariffType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}PurchaseModelBaseType">
 *       &lt;sequence>
 *         &lt;element name="accumPeriod" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}PeriodType" minOccurs="0"/>
 *         &lt;element name="usageCostUnitValue" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}PriceType"/>
 *         &lt;element name="usageCost" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}TariffType"/>
 *         &lt;element name="accumQuantity" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PurchaseModelUsageTariffType", propOrder = {
    "accumPeriod",
    "usageCostUnitValue",
    "usageCost",
    "accumQuantity"
})
public class PurchaseModelUsageTariffType
    extends PurchaseModelBaseType
{

    protected PeriodType accumPeriod;
    @XmlElement(required = true)
    protected PriceType usageCostUnitValue;
    @XmlElement(required = true)
    protected TariffType usageCost;
    protected Integer accumQuantity;

    /**
     * Gets the value of the accumPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link PeriodType }
     *     
     */
    public PeriodType getAccumPeriod() {
        return accumPeriod;
    }

    /**
     * Sets the value of the accumPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeriodType }
     *     
     */
    public void setAccumPeriod(PeriodType value) {
        this.accumPeriod = value;
    }

    /**
     * Gets the value of the usageCostUnitValue property.
     * 
     * @return
     *     possible object is
     *     {@link PriceType }
     *     
     */
    public PriceType getUsageCostUnitValue() {
        return usageCostUnitValue;
    }

    /**
     * Sets the value of the usageCostUnitValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceType }
     *     
     */
    public void setUsageCostUnitValue(PriceType value) {
        this.usageCostUnitValue = value;
    }

    /**
     * Gets the value of the usageCost property.
     * 
     * @return
     *     possible object is
     *     {@link TariffType }
     *     
     */
    public TariffType getUsageCost() {
        return usageCost;
    }

    /**
     * Sets the value of the usageCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link TariffType }
     *     
     */
    public void setUsageCost(TariffType value) {
        this.usageCost = value;
    }

    /**
     * Gets the value of the accumQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAccumQuantity() {
        return accumQuantity;
    }

    /**
     * Sets the value of the accumQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAccumQuantity(Integer value) {
        this.accumQuantity = value;
    }

}
