//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 08:40:35 AM CEST 
//


package com.telefonica.schemas.unica.soap.charging.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UnitsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UnitsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="genericUnits" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *         &lt;element name="purchaseModelUnitAndAction" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="renewalAction" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="usageType" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="extension" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}ExtensionType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UnitsType", propOrder = {
    "genericUnits",
    "purchaseModelUnitAndAction",
    "renewalAction",
    "usageType",
    "extension"
})
public class UnitsType {

    @XmlSchemaType(name = "unsignedInt")
    protected long genericUnits;
    @XmlSchemaType(name = "unsignedInt")
    protected Long purchaseModelUnitAndAction;
    @XmlSchemaType(name = "unsignedInt")
    protected Long renewalAction;
    @XmlSchemaType(name = "unsignedInt")
    protected Long usageType;
    protected List<ExtensionType> extension;

    /**
     * Gets the value of the genericUnits property.
     * 
     */
    public long getGenericUnits() {
        return genericUnits;
    }

    /**
     * Sets the value of the genericUnits property.
     * 
     */
    public void setGenericUnits(long value) {
        this.genericUnits = value;
    }

    /**
     * Gets the value of the purchaseModelUnitAndAction property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPurchaseModelUnitAndAction() {
        return purchaseModelUnitAndAction;
    }

    /**
     * Sets the value of the purchaseModelUnitAndAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPurchaseModelUnitAndAction(Long value) {
        this.purchaseModelUnitAndAction = value;
    }

    /**
     * Gets the value of the renewalAction property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRenewalAction() {
        return renewalAction;
    }

    /**
     * Sets the value of the renewalAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRenewalAction(Long value) {
        this.renewalAction = value;
    }

    /**
     * Gets the value of the usageType property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getUsageType() {
        return usageType;
    }

    /**
     * Sets the value of the usageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setUsageType(Long value) {
        this.usageType = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtensionType }
     * 
     * 
     */
    public List<ExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<ExtensionType>();
        }
        return this.extension;
    }

}
