//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.09 at 09:17:46 AM CEST 
//


package com.telefonica.schemas.unica.soap.charging.v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UserPaymentMethodType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserPaymentMethodType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PaymentMethodId" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}PaymentMethodTypes" minOccurs="0"/>
 *         &lt;element name="externalChargeData" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}ExternalChargeDataType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserPaymentMethodType", propOrder = {
    "paymentMethodId",
    "externalChargeData"
})
public class UserPaymentMethodType {

    @XmlElementRef(name = "PaymentMethodId", namespace = "http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1", type = JAXBElement.class)
    protected JAXBElement<PaymentMethodTypes> paymentMethodId;
    @XmlElementRef(name = "externalChargeData", namespace = "http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1", type = JAXBElement.class)
    protected JAXBElement<ExternalChargeDataType> externalChargeData;

    /**
     * Gets the value of the paymentMethodId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PaymentMethodTypes }{@code >}
     *     
     */
    public JAXBElement<PaymentMethodTypes> getPaymentMethodId() {
        return paymentMethodId;
    }

    /**
     * Sets the value of the paymentMethodId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PaymentMethodTypes }{@code >}
     *     
     */
    public void setPaymentMethodId(JAXBElement<PaymentMethodTypes> value) {
        this.paymentMethodId = ((JAXBElement<PaymentMethodTypes> ) value);
    }

    /**
     * Gets the value of the externalChargeData property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ExternalChargeDataType }{@code >}
     *     
     */
    public JAXBElement<ExternalChargeDataType> getExternalChargeData() {
        return externalChargeData;
    }

    /**
     * Sets the value of the externalChargeData property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ExternalChargeDataType }{@code >}
     *     
     */
    public void setExternalChargeData(JAXBElement<ExternalChargeDataType> value) {
        this.externalChargeData = ((JAXBElement<ExternalChargeDataType> ) value);
    }

}
