//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.18 at 12:38:21 PM CEST 
//


package com.telefonica.schemas.unica.soap.common.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ErrorInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ErrorInformationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="clientException" type="{http://www.telefonica.com/schemas/UNICA/SOAP/common/v1}ClientExceptionType"/>
 *         &lt;element name="serverException" type="{http://www.telefonica.com/schemas/UNICA/SOAP/common/v1}ServerExceptionType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ErrorInformationType", propOrder = {
    "clientException",
    "serverException"
})
public class ErrorInformationType {

    protected ClientExceptionType clientException;
    protected ServerExceptionType serverException;

    /**
     * Gets the value of the clientException property.
     * 
     * @return
     *     possible object is
     *     {@link ClientExceptionType }
     *     
     */
    public ClientExceptionType getClientException() {
        return clientException;
    }

    /**
     * Sets the value of the clientException property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClientExceptionType }
     *     
     */
    public void setClientException(ClientExceptionType value) {
        this.clientException = value;
    }

    /**
     * Gets the value of the serverException property.
     * 
     * @return
     *     possible object is
     *     {@link ServerExceptionType }
     *     
     */
    public ServerExceptionType getServerException() {
        return serverException;
    }

    /**
     * Sets the value of the serverException property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServerExceptionType }
     *     
     */
    public void setServerException(ServerExceptionType value) {
        this.serverException = value;
    }

}
