//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.29 at 01:15:52 PM CET 
//


package es.tid.neosdp.bluevia.schemas.mms.v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.tid.neosdp.bluevia.schemas.mms.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ReceivedMessages_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/mms/v1/", "receivedMessages");
    private final static QName _ReceivedMessageAsync_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/mms/v1/", "receivedMessageAsync");
    private final static QName _MessageDeliveryStatus_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/mms/v1/", "messageDeliveryStatus");
    private final static QName _ServerException_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/common/v1", "ServerException");
    private final static QName _MessageNotification_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/mms/v1/", "messageNotification");
    private final static QName _ClientException_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/common/v1", "ClientException");
    private final static QName _Message_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/mms/v1/", "message");
    private final static QName _DeliveryStatusUpdate_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/mms/v1/", "deliveryStatusUpdate");
    private final static QName _DeliveryReceiptNotification_QNAME = new QName("http://www.telefonica.com/schemas/UNICA/REST/mms/v1/", "deliveryReceiptNotification");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.tid.neosdp.bluevia.schemas.mms.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeliveryReceiptNotificationType }
     * 
     */
    public DeliveryReceiptNotificationType createDeliveryReceiptNotificationType() {
        return new DeliveryReceiptNotificationType();
    }

    /**
     * Create an instance of {@link ReceivedMessagesType }
     * 
     */
    public ReceivedMessagesType createReceivedMessagesType() {
        return new ReceivedMessagesType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link ClientExceptionType }
     * 
     */
    public ClientExceptionType createClientExceptionType() {
        return new ClientExceptionType();
    }

    /**
     * Create an instance of {@link SimpleReferenceType }
     * 
     */
    public SimpleReferenceType createSimpleReferenceType() {
        return new SimpleReferenceType();
    }

    /**
     * Create an instance of {@link ServerExceptionType }
     * 
     */
    public ServerExceptionType createServerExceptionType() {
        return new ServerExceptionType();
    }

    /**
     * Create an instance of {@link IpAddressType }
     * 
     */
    public IpAddressType createIpAddressType() {
        return new IpAddressType();
    }

    /**
     * Create an instance of {@link UserIdType }
     * 
     */
    public UserIdType createUserIdType() {
        return new UserIdType();
    }

    /**
     * Create an instance of {@link ExtensionType }
     * 
     */
    public ExtensionType createExtensionType() {
        return new ExtensionType();
    }

    /**
     * Create an instance of {@link ReceivedMessageAsyncType }
     * 
     */
    public ReceivedMessageAsyncType createReceivedMessageAsyncType() {
        return new ReceivedMessageAsyncType();
    }

    /**
     * Create an instance of {@link MessageReferenceType }
     * 
     */
    public MessageReferenceType createMessageReferenceType() {
        return new MessageReferenceType();
    }

    /**
     * Create an instance of {@link OtherIdType }
     * 
     */
    public OtherIdType createOtherIdType() {
        return new OtherIdType();
    }

    /**
     * Create an instance of {@link DeliveryStatusUpdateType }
     * 
     */
    public DeliveryStatusUpdateType createDeliveryStatusUpdateType() {
        return new DeliveryStatusUpdateType();
    }

    /**
     * Create an instance of {@link MessageDeliveryStatusType }
     * 
     */
    public MessageDeliveryStatusType createMessageDeliveryStatusType() {
        return new MessageDeliveryStatusType();
    }

    /**
     * Create an instance of {@link MessageNotificationType }
     * 
     */
    public MessageNotificationType createMessageNotificationType() {
        return new MessageNotificationType();
    }

    /**
     * Create an instance of {@link DeliveryInformationType }
     * 
     */
    public DeliveryInformationType createDeliveryInformationType() {
        return new DeliveryInformationType();
    }

    /**
     * Create an instance of {@link MessageURIType }
     * 
     */
    public MessageURIType createMessageURIType() {
        return new MessageURIType();
    }

    /**
     * Create an instance of {@link MessageType }
     * 
     */
    public MessageType createMessageType() {
        return new MessageType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReceivedMessagesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/mms/v1/", name = "receivedMessages")
    public JAXBElement<ReceivedMessagesType> createReceivedMessages(ReceivedMessagesType value) {
        return new JAXBElement<ReceivedMessagesType>(_ReceivedMessages_QNAME, ReceivedMessagesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReceivedMessageAsyncType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/mms/v1/", name = "receivedMessageAsync")
    public JAXBElement<ReceivedMessageAsyncType> createReceivedMessageAsync(ReceivedMessageAsyncType value) {
        return new JAXBElement<ReceivedMessageAsyncType>(_ReceivedMessageAsync_QNAME, ReceivedMessageAsyncType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageDeliveryStatusType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/mms/v1/", name = "messageDeliveryStatus")
    public JAXBElement<MessageDeliveryStatusType> createMessageDeliveryStatus(MessageDeliveryStatusType value) {
        return new JAXBElement<MessageDeliveryStatusType>(_MessageDeliveryStatus_QNAME, MessageDeliveryStatusType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServerExceptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/common/v1", name = "ServerException")
    public JAXBElement<ServerExceptionType> createServerException(ServerExceptionType value) {
        return new JAXBElement<ServerExceptionType>(_ServerException_QNAME, ServerExceptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageNotificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/mms/v1/", name = "messageNotification")
    public JAXBElement<MessageNotificationType> createMessageNotification(MessageNotificationType value) {
        return new JAXBElement<MessageNotificationType>(_MessageNotification_QNAME, MessageNotificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClientExceptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/common/v1", name = "ClientException")
    public JAXBElement<ClientExceptionType> createClientException(ClientExceptionType value) {
        return new JAXBElement<ClientExceptionType>(_ClientException_QNAME, ClientExceptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/mms/v1/", name = "message")
    public JAXBElement<MessageType> createMessage(MessageType value) {
        return new JAXBElement<MessageType>(_Message_QNAME, MessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeliveryStatusUpdateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/mms/v1/", name = "deliveryStatusUpdate")
    public JAXBElement<DeliveryStatusUpdateType> createDeliveryStatusUpdate(DeliveryStatusUpdateType value) {
        return new JAXBElement<DeliveryStatusUpdateType>(_DeliveryStatusUpdate_QNAME, DeliveryStatusUpdateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeliveryReceiptNotificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telefonica.com/schemas/UNICA/REST/mms/v1/", name = "deliveryReceiptNotification")
    public JAXBElement<DeliveryReceiptNotificationType> createDeliveryReceiptNotification(DeliveryReceiptNotificationType value) {
        return new JAXBElement<DeliveryReceiptNotificationType>(_DeliveryReceiptNotification_QNAME, DeliveryReceiptNotificationType.class, null, value);
    }

}
