//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.30 at 03:28:52 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.telefonica.com/schemas/UNICA/REST/transactionStorage/extensions/v1/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.telefonica.schemas.unica.rest.transactionstorage.extensions.v1;
