//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.22 at 08:53:40 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://api.bluevia.com/schemas/v2/common", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package es.tid.neosdp.bluevia.schemas.location.v2;
