//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.09 at 10:03:38 AM CET 
//


package es.tid.neosdp.bluevia.schemas.advertising.v2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.tid.neosdp.bluevia.schemas.advertising.v2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Ad_QNAME = new QName("http://api.bluevia.com/schemas/v2/advertising", "ad");
    private final static QName _AdList_QNAME = new QName("http://api.bluevia.com/schemas/v2/advertising", "adList");
    private final static QName _Exception_QNAME = new QName("http://api.bluevia.com/schemas/v2/common", "exception");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.tid.neosdp.bluevia.schemas.advertising.v2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AdListType }
     * 
     */
    public AdListType createAdListType() {
        return new AdListType();
    }

    /**
     * Create an instance of {@link NameValuePairType }
     * 
     */
    public NameValuePairType createNameValuePairType() {
        return new NameValuePairType();
    }

    /**
     * Create an instance of {@link ExceptionType }
     * 
     */
    public ExceptionType createExceptionType() {
        return new ExceptionType();
    }

    /**
     * Create an instance of {@link AdType }
     * 
     */
    public AdType createAdType() {
        return new AdType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.bluevia.com/schemas/v2/advertising", name = "ad")
    public JAXBElement<AdType> createAd(AdType value) {
        return new JAXBElement<AdType>(_Ad_QNAME, AdType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.bluevia.com/schemas/v2/advertising", name = "adList")
    public JAXBElement<AdListType> createAdList(AdListType value) {
        return new JAXBElement<AdListType>(_AdList_QNAME, AdListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExceptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://api.bluevia.com/schemas/v2/common", name = "exception")
    public JAXBElement<ExceptionType> createException(ExceptionType value) {
        return new JAXBElement<ExceptionType>(_Exception_QNAME, ExceptionType.class, null, value);
    }

}
