//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.09 at 09:34:13 AM CEST 
//


package com.telefonica.schemas.unica.rpc.common.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Information about a participant in a call
 * 
 * <p>Java class for CallParticipantInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CallParticipantInformationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="callParticipantIdentifier" type="{http://www.telefonica.com/schemas/UNICA/RPC/common/v1}UserIdType"/>
 *         &lt;element name="callParticipantStatus" type="{http://www.telefonica.com/schemas/UNICA/RPC/common/v1}CallParticipantStatusType"/>
 *         &lt;element name="callParticipantStartTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="callParticipantDuration" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="callParticipantTerminationCause" type="{http://www.telefonica.com/schemas/UNICA/RPC/common/v1}CallParticipantTerminationCauseType" minOccurs="0"/>
 *         &lt;element name="mediaInfo" type="{http://www.telefonica.com/schemas/UNICA/RPC/common/v1}MediaInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CallParticipantInformationType", propOrder = {
    "callParticipantIdentifier",
    "callParticipantStatus",
    "callParticipantStartTime",
    "callParticipantDuration",
    "callParticipantTerminationCause",
    "mediaInfo"
})
public class CallParticipantInformationType {

    @XmlElement(required = true)
    protected UserIdType callParticipantIdentifier;
    @XmlElement(required = true)
    protected CallParticipantStatusType callParticipantStatus;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar callParticipantStartTime;
    protected Integer callParticipantDuration;
    protected CallParticipantTerminationCauseType callParticipantTerminationCause;
    protected List<MediaInfoType> mediaInfo;

    /**
     * Gets the value of the callParticipantIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link UserIdType }
     *     
     */
    public UserIdType getCallParticipantIdentifier() {
        return callParticipantIdentifier;
    }

    /**
     * Sets the value of the callParticipantIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserIdType }
     *     
     */
    public void setCallParticipantIdentifier(UserIdType value) {
        this.callParticipantIdentifier = value;
    }

    /**
     * Gets the value of the callParticipantStatus property.
     * 
     * @return
     *     possible object is
     *     {@link CallParticipantStatusType }
     *     
     */
    public CallParticipantStatusType getCallParticipantStatus() {
        return callParticipantStatus;
    }

    /**
     * Sets the value of the callParticipantStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link CallParticipantStatusType }
     *     
     */
    public void setCallParticipantStatus(CallParticipantStatusType value) {
        this.callParticipantStatus = value;
    }

    /**
     * Gets the value of the callParticipantStartTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCallParticipantStartTime() {
        return callParticipantStartTime;
    }

    /**
     * Sets the value of the callParticipantStartTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCallParticipantStartTime(XMLGregorianCalendar value) {
        this.callParticipantStartTime = value;
    }

    /**
     * Gets the value of the callParticipantDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCallParticipantDuration() {
        return callParticipantDuration;
    }

    /**
     * Sets the value of the callParticipantDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCallParticipantDuration(Integer value) {
        this.callParticipantDuration = value;
    }

    /**
     * Gets the value of the callParticipantTerminationCause property.
     * 
     * @return
     *     possible object is
     *     {@link CallParticipantTerminationCauseType }
     *     
     */
    public CallParticipantTerminationCauseType getCallParticipantTerminationCause() {
        return callParticipantTerminationCause;
    }

    /**
     * Sets the value of the callParticipantTerminationCause property.
     * 
     * @param value
     *     allowed object is
     *     {@link CallParticipantTerminationCauseType }
     *     
     */
    public void setCallParticipantTerminationCause(CallParticipantTerminationCauseType value) {
        this.callParticipantTerminationCause = value;
    }

    /**
     * Gets the value of the mediaInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mediaInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMediaInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MediaInfoType }
     * 
     * 
     */
    public List<MediaInfoType> getMediaInfo() {
        if (mediaInfo == null) {
            mediaInfo = new ArrayList<MediaInfoType>();
        }
        return this.mediaInfo;
    }

}
