//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.09 at 09:34:13 AM CEST 
//


package com.telefonica.schemas.unica.rpc.common.v1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MediaTypesType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MediaTypesType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Audio"/>
 *     &lt;enumeration value="Video"/>
 *     &lt;enumeration value="Chat"/>
 *     &lt;enumeration value="Data"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MediaTypesType")
@XmlEnum
public enum MediaTypesType {

    @XmlEnumValue("Audio")
    AUDIO("Audio"),
    @XmlEnumValue("Video")
    VIDEO("Video"),
    @XmlEnumValue("Chat")
    CHAT("Chat"),
    @XmlEnumValue("Data")
    DATA("Data");
    private final String value;

    MediaTypesType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MediaTypesType fromValue(String v) {
        for (MediaTypesType c: MediaTypesType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
