//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.09 at 09:34:13 AM CEST 
//


package com.telefonica.schemas.unica.rpc.common.v1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.telefonica.schemas.unica.rpc.common.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.telefonica.schemas.unica.rpc.common.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link CallParticipantInformationType }
     * 
     */
    public CallParticipantInformationType createCallParticipantInformationType() {
        return new CallParticipantInformationType();
    }

    /**
     * Create an instance of {@link SearchParamsType }
     * 
     */
    public SearchParamsType createSearchParamsType() {
        return new SearchParamsType();
    }

    /**
     * Create an instance of {@link CallSessionInformationType }
     * 
     */
    public CallSessionInformationType createCallSessionInformationType() {
        return new CallSessionInformationType();
    }

    /**
     * Create an instance of {@link OtherIdType }
     * 
     */
    public OtherIdType createOtherIdType() {
        return new OtherIdType();
    }

    /**
     * Create an instance of {@link NameValuePairType }
     * 
     */
    public NameValuePairType createNameValuePairType() {
        return new NameValuePairType();
    }

    /**
     * Create an instance of {@link IpAddressType }
     * 
     */
    public IpAddressType createIpAddressType() {
        return new IpAddressType();
    }

    /**
     * Create an instance of {@link UserIdType }
     * 
     */
    public UserIdType createUserIdType() {
        return new UserIdType();
    }

    /**
     * Create an instance of {@link MediaType }
     * 
     */
    public MediaType createMediaType() {
        return new MediaType();
    }

    /**
     * Create an instance of {@link ValueType }
     * 
     */
    public ValueType createValueType() {
        return new ValueType();
    }

    /**
     * Create an instance of {@link CallParticipantStatusType }
     * 
     */
    public CallParticipantStatusType createCallParticipantStatusType() {
        return new CallParticipantStatusType();
    }

    /**
     * Create an instance of {@link FilterParamsType }
     * 
     */
    public FilterParamsType createFilterParamsType() {
        return new FilterParamsType();
    }

    /**
     * Create an instance of {@link SimpleReferenceType }
     * 
     */
    public SimpleReferenceType createSimpleReferenceType() {
        return new SimpleReferenceType();
    }

    /**
     * Create an instance of {@link CallParticipantTerminationCauseType }
     * 
     */
    public CallParticipantTerminationCauseType createCallParticipantTerminationCauseType() {
        return new CallParticipantTerminationCauseType();
    }

    /**
     * Create an instance of {@link ExtensionType }
     * 
     */
    public ExtensionType createExtensionType() {
        return new ExtensionType();
    }

    /**
     * Create an instance of {@link MediaDirectionType }
     * 
     */
    public MediaDirectionType createMediaDirectionType() {
        return new MediaDirectionType();
    }

    /**
     * Create an instance of {@link MediaInfoType }
     * 
     */
    public MediaInfoType createMediaInfoType() {
        return new MediaInfoType();
    }

}
