//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.20 at 01:33:48 PM CEST 
//


package com.telefonica.schemas.unica.rest.transactionstorage.v1;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PaymentAmountType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentAmountType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="chargingInformation" type="{http://www.telefonica.com/schemas/UNICA/REST/transactionStorage/v1/}ChargingInformationType"/>
 *         &lt;element name="chargingMetaData" type="{http://www.telefonica.com/schemas/UNICA/REST/transactionStorage/v1/}ChargingMetaDataType" minOccurs="0"/>
 *         &lt;element name="totalAmountCharged" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="totalAmountRefunded" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="totalAmountCredited" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="totalTaxAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="amountReserved" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentAmountType", propOrder = {
    "chargingInformation",
    "chargingMetaData",
    "totalAmountCharged",
    "totalAmountRefunded",
    "totalAmountCredited",
    "totalTaxAmount",
    "amountReserved"
})
public class PaymentAmountType {

    @XmlElement(required = true)
    protected ChargingInformationType chargingInformation;
    protected ChargingMetaDataType chargingMetaData;
    protected BigDecimal totalAmountCharged;
    protected BigDecimal totalAmountRefunded;
    protected BigDecimal totalAmountCredited;
    protected BigDecimal totalTaxAmount;
    protected BigDecimal amountReserved;

    /**
     * Gets the value of the chargingInformation property.
     * 
     * @return
     *     possible object is
     *     {@link ChargingInformationType }
     *     
     */
    public ChargingInformationType getChargingInformation() {
        return chargingInformation;
    }

    /**
     * Sets the value of the chargingInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChargingInformationType }
     *     
     */
    public void setChargingInformation(ChargingInformationType value) {
        this.chargingInformation = value;
    }

    /**
     * Gets the value of the chargingMetaData property.
     * 
     * @return
     *     possible object is
     *     {@link ChargingMetaDataType }
     *     
     */
    public ChargingMetaDataType getChargingMetaData() {
        return chargingMetaData;
    }

    /**
     * Sets the value of the chargingMetaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChargingMetaDataType }
     *     
     */
    public void setChargingMetaData(ChargingMetaDataType value) {
        this.chargingMetaData = value;
    }

    /**
     * Gets the value of the totalAmountCharged property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalAmountCharged() {
        return totalAmountCharged;
    }

    /**
     * Sets the value of the totalAmountCharged property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalAmountCharged(BigDecimal value) {
        this.totalAmountCharged = value;
    }

    /**
     * Gets the value of the totalAmountRefunded property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalAmountRefunded() {
        return totalAmountRefunded;
    }

    /**
     * Sets the value of the totalAmountRefunded property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalAmountRefunded(BigDecimal value) {
        this.totalAmountRefunded = value;
    }

    /**
     * Gets the value of the totalAmountCredited property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalAmountCredited() {
        return totalAmountCredited;
    }

    /**
     * Sets the value of the totalAmountCredited property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalAmountCredited(BigDecimal value) {
        this.totalAmountCredited = value;
    }

    /**
     * Gets the value of the totalTaxAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalTaxAmount() {
        return totalTaxAmount;
    }

    /**
     * Sets the value of the totalTaxAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalTaxAmount(BigDecimal value) {
        this.totalTaxAmount = value;
    }

    /**
     * Gets the value of the amountReserved property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmountReserved() {
        return amountReserved;
    }

    /**
     * Sets the value of the amountReserved property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmountReserved(BigDecimal value) {
        this.amountReserved = value;
    }

}
