//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.20 at 01:33:48 PM CEST 
//


package com.telefonica.schemas.unica.rest.transactionstorage.v1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransactionOperationTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TransactionOperationTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Charge"/>
 *     &lt;enumeration value="Refund"/>
 *     &lt;enumeration value="Capture"/>
 *     &lt;enumeration value="Reserve"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TransactionOperationTypeType")
@XmlEnum
public enum TransactionOperationTypeType {

    @XmlEnumValue("Charge")
    CHARGE("Charge"),
    @XmlEnumValue("Refund")
    REFUND("Refund"),
    @XmlEnumValue("Capture")
    CAPTURE("Capture"),
    @XmlEnumValue("Reserve")
    RESERVE("Reserve");
    private final String value;

    TransactionOperationTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TransactionOperationTypeType fromValue(String v) {
        for (TransactionOperationTypeType c: TransactionOperationTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
