//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.09 at 11:22:41 AM CEST 
//


package com.telefonica.schemas.unica.rest.payment.v3;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.telefonica.schemas.unica.rest.common.v2.AddressType;


/**
 * <p>Java class for MerchantProfileType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MerchantProfileType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="merchantId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="merchantPassword" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="merchantTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="merchantName" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="merchantLegalForm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="merchantPhone" type="{http://www.telefonica.com/schemas/UNICA/REST/common/v2}E164Type" minOccurs="0"/>
 *         &lt;element name="merchantMail" type="{http://www.telefonica.com/schemas/UNICA/REST/common/v2}EmailAddressType" minOccurs="0"/>
 *         &lt;element name="merchantAddress" type="{http://www.telefonica.com/schemas/UNICA/REST/common/v2}AddressType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MerchantProfileType", propOrder = {
    "merchantId",
    "merchantPassword",
    "merchantTitle",
    "merchantName",
    "merchantLegalForm",
    "merchantPhone",
    "merchantMail",
    "merchantAddress"
})
public class MerchantProfileType {

    @XmlElement(required = true)
    protected String merchantId;
    protected String merchantPassword;
    protected String merchantTitle;
    protected BigDecimal merchantName;
    protected String merchantLegalForm;
    protected String merchantPhone;
    protected String merchantMail;
    protected AddressType merchantAddress;

    /**
     * Gets the value of the merchantId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * Sets the value of the merchantId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantId(String value) {
        this.merchantId = value;
    }

    /**
     * Gets the value of the merchantPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantPassword() {
        return merchantPassword;
    }

    /**
     * Sets the value of the merchantPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantPassword(String value) {
        this.merchantPassword = value;
    }

    /**
     * Gets the value of the merchantTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantTitle() {
        return merchantTitle;
    }

    /**
     * Sets the value of the merchantTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantTitle(String value) {
        this.merchantTitle = value;
    }

    /**
     * Gets the value of the merchantName property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMerchantName() {
        return merchantName;
    }

    /**
     * Sets the value of the merchantName property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMerchantName(BigDecimal value) {
        this.merchantName = value;
    }

    /**
     * Gets the value of the merchantLegalForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantLegalForm() {
        return merchantLegalForm;
    }

    /**
     * Sets the value of the merchantLegalForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantLegalForm(String value) {
        this.merchantLegalForm = value;
    }

    /**
     * Gets the value of the merchantPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantPhone() {
        return merchantPhone;
    }

    /**
     * Sets the value of the merchantPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantPhone(String value) {
        this.merchantPhone = value;
    }

    /**
     * Gets the value of the merchantMail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantMail() {
        return merchantMail;
    }

    /**
     * Sets the value of the merchantMail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantMail(String value) {
        this.merchantMail = value;
    }

    /**
     * Gets the value of the merchantAddress property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getMerchantAddress() {
        return merchantAddress;
    }

    /**
     * Sets the value of the merchantAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setMerchantAddress(AddressType value) {
        this.merchantAddress = value;
    }

}
