//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.09 at 11:22:41 AM CEST 
//


package com.telefonica.schemas.unica.rest.payment.v3;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReservationInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReservationInformationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="reservationClass" type="{http://www.telefonica.com/schemas/UNICA/REST/payment/v3/}ReservationClassType"/>
 *         &lt;element name="amountReservedRate" type="{http://www.telefonica.com/schemas/UNICA/REST/payment/v3/}AmountRateType" minOccurs="0"/>
 *         &lt;element name="initialAmountReserved" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReservationInformationType", propOrder = {
    "reservationClass",
    "amountReservedRate",
    "initialAmountReserved"
})
public class ReservationInformationType {

    @XmlElement(required = true)
    protected ReservationClassType reservationClass;
    protected AmountRateType amountReservedRate;
    protected BigDecimal initialAmountReserved;

    /**
     * Gets the value of the reservationClass property.
     * 
     * @return
     *     possible object is
     *     {@link ReservationClassType }
     *     
     */
    public ReservationClassType getReservationClass() {
        return reservationClass;
    }

    /**
     * Sets the value of the reservationClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReservationClassType }
     *     
     */
    public void setReservationClass(ReservationClassType value) {
        this.reservationClass = value;
    }

    /**
     * Gets the value of the amountReservedRate property.
     * 
     * @return
     *     possible object is
     *     {@link AmountRateType }
     *     
     */
    public AmountRateType getAmountReservedRate() {
        return amountReservedRate;
    }

    /**
     * Sets the value of the amountReservedRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountRateType }
     *     
     */
    public void setAmountReservedRate(AmountRateType value) {
        this.amountReservedRate = value;
    }

    /**
     * Gets the value of the initialAmountReserved property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInitialAmountReserved() {
        return initialAmountReserved;
    }

    /**
     * Sets the value of the initialAmountReserved property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInitialAmountReserved(BigDecimal value) {
        this.initialAmountReserved = value;
    }

}
