//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.09 at 11:22:41 AM CEST 
//


package com.telefonica.schemas.unica.rest.payment.v3;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for SubscriptionInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubscriptionInformationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="chargingInformation" type="{http://www.telefonica.com/schemas/UNICA/REST/payment/v3/}ChargingInformationType"/>
 *         &lt;element name="chargingMetaData" type="{http://www.telefonica.com/schemas/UNICA/REST/payment/v3/}ChargingMetaDataType" minOccurs="0"/>
 *         &lt;element name="subscriptionStartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="subscriptionTerminationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="subscriptionTerminationText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="period" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="periodUnit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="maxTotalAmountPerPeriod" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="maxCapturesPerPeriod" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubscriptionInformationType", propOrder = {
    "chargingInformation",
    "chargingMetaData",
    "subscriptionStartDate",
    "subscriptionTerminationDate",
    "subscriptionTerminationText",
    "period",
    "periodUnit",
    "maxTotalAmountPerPeriod",
    "maxCapturesPerPeriod"
})
public class SubscriptionInformationType {

    @XmlElement(required = true)
    protected ChargingInformationType chargingInformation;
    protected ChargingMetaDataType chargingMetaData;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar subscriptionStartDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar subscriptionTerminationDate;
    protected String subscriptionTerminationText;
    protected BigInteger period;
    protected String periodUnit;
    protected BigDecimal maxTotalAmountPerPeriod;
    protected BigDecimal maxCapturesPerPeriod;

    /**
     * Gets the value of the chargingInformation property.
     * 
     * @return
     *     possible object is
     *     {@link ChargingInformationType }
     *     
     */
    public ChargingInformationType getChargingInformation() {
        return chargingInformation;
    }

    /**
     * Sets the value of the chargingInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChargingInformationType }
     *     
     */
    public void setChargingInformation(ChargingInformationType value) {
        this.chargingInformation = value;
    }

    /**
     * Gets the value of the chargingMetaData property.
     * 
     * @return
     *     possible object is
     *     {@link ChargingMetaDataType }
     *     
     */
    public ChargingMetaDataType getChargingMetaData() {
        return chargingMetaData;
    }

    /**
     * Sets the value of the chargingMetaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChargingMetaDataType }
     *     
     */
    public void setChargingMetaData(ChargingMetaDataType value) {
        this.chargingMetaData = value;
    }

    /**
     * Gets the value of the subscriptionStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSubscriptionStartDate() {
        return subscriptionStartDate;
    }

    /**
     * Sets the value of the subscriptionStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSubscriptionStartDate(XMLGregorianCalendar value) {
        this.subscriptionStartDate = value;
    }

    /**
     * Gets the value of the subscriptionTerminationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSubscriptionTerminationDate() {
        return subscriptionTerminationDate;
    }

    /**
     * Sets the value of the subscriptionTerminationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSubscriptionTerminationDate(XMLGregorianCalendar value) {
        this.subscriptionTerminationDate = value;
    }

    /**
     * Gets the value of the subscriptionTerminationText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubscriptionTerminationText() {
        return subscriptionTerminationText;
    }

    /**
     * Sets the value of the subscriptionTerminationText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscriptionTerminationText(String value) {
        this.subscriptionTerminationText = value;
    }

    /**
     * Gets the value of the period property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPeriod(BigInteger value) {
        this.period = value;
    }

    /**
     * Gets the value of the periodUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodUnit() {
        return periodUnit;
    }

    /**
     * Sets the value of the periodUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodUnit(String value) {
        this.periodUnit = value;
    }

    /**
     * Gets the value of the maxTotalAmountPerPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxTotalAmountPerPeriod() {
        return maxTotalAmountPerPeriod;
    }

    /**
     * Sets the value of the maxTotalAmountPerPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxTotalAmountPerPeriod(BigDecimal value) {
        this.maxTotalAmountPerPeriod = value;
    }

    /**
     * Gets the value of the maxCapturesPerPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxCapturesPerPeriod() {
        return maxCapturesPerPeriod;
    }

    /**
     * Sets the value of the maxCapturesPerPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxCapturesPerPeriod(BigDecimal value) {
        this.maxCapturesPerPeriod = value;
    }

}
