//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.09 at 11:22:41 AM CEST 
//


package com.telefonica.schemas.unica.rest.payment.v3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UserAuthKindType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="UserAuthKindType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Direct"/>
 *     &lt;enumeration value="Code"/>
 *     &lt;enumeration value="Oauth1"/>
 *     &lt;enumeration value="Oauth2"/>
 *     &lt;enumeration value="WWW"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "UserAuthKindType")
@XmlEnum
public enum UserAuthKindType {

    @XmlEnumValue("Direct")
    DIRECT("Direct"),
    @XmlEnumValue("Code")
    CODE("Code"),
    @XmlEnumValue("Oauth1")
    OAUTH_1("Oauth1"),
    @XmlEnumValue("Oauth2")
    OAUTH_2("Oauth2"),
    WWW("WWW");
    private final String value;

    UserAuthKindType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static UserAuthKindType fromValue(String v) {
        for (UserAuthKindType c: UserAuthKindType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
