//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 08:40:35 AM CEST 
//


package com.telefonica.wsdl.unica.soap.charging.v1.interfaces;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.telefonica.schemas.unica.soap.charging.v1.ExtensionType;
import com.telefonica.schemas.unica.soap.common.v1.UserIdType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="requestId" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}RequestIdType"/>
 *         &lt;element name="requestNumber" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}RequestNumberType"/>
 *         &lt;element name="timestamp" type="{http://www.telefonica.com/schemas/UNICA/SOAP/common/v1}TimestampType"/>
 *         &lt;element name="senderIdentity" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}SenderIdentityType"/>
 *         &lt;element name="serviceContextId" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}ServiceContextIdType"/>
 *         &lt;element name="userId" type="{http://www.telefonica.com/schemas/UNICA/SOAP/common/v1}UserIdType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="operatorId" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}OperatorIdType" minOccurs="0"/>
 *         &lt;element name="subsTimeZone" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}TimeZoneType" minOccurs="0"/>
 *         &lt;element name="locTimeZone" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}TimeZoneType" minOccurs="0"/>
 *         &lt;element name="rollback" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}RollbackType" minOccurs="0"/>
 *         &lt;element name="code1" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}CodeType" minOccurs="0"/>
 *         &lt;element name="code2" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}CodeType" minOccurs="0"/>
 *         &lt;element name="code3" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}CodeType" minOccurs="0"/>
 *         &lt;element name="purchaseCode" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}PurchaseCodeType" minOccurs="0"/>
 *         &lt;element name="subPurchaseCode" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}SubPurchaseCodeType" minOccurs="0"/>
 *         &lt;element name="additionalInfo" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}AdditionalInfoType" minOccurs="0"/>
 *         &lt;element name="extension" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}ExtensionType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "requestId",
    "requestNumber",
    "timestamp",
    "senderIdentity",
    "serviceContextId",
    "userId",
    "operatorId",
    "subsTimeZone",
    "locTimeZone",
    "rollback",
    "code1",
    "code2",
    "code3",
    "purchaseCode",
    "subPurchaseCode",
    "additionalInfo",
    "extension"
})
@XmlRootElement(name = "cancelRenewal")
public class CancelRenewal {

    @XmlElement(required = true)
    protected String requestId;
    protected int requestNumber;
    @XmlElement(required = true)
    protected XMLGregorianCalendar timestamp;
    @XmlElement(required = true)
    protected String senderIdentity;
    @XmlElement(required = true)
    protected String serviceContextId;
    protected List<UserIdType> userId;
    protected String operatorId;
    protected String subsTimeZone;
    protected String locTimeZone;
    protected Boolean rollback;
    protected Integer code1;
    protected Integer code2;
    protected Integer code3;
    protected Integer purchaseCode;
    protected Integer subPurchaseCode;
    protected String additionalInfo;
    protected List<ExtensionType> extension;

    /**
     * Gets the value of the requestId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * Sets the value of the requestId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestId(String value) {
        this.requestId = value;
    }

    /**
     * Gets the value of the requestNumber property.
     * 
     */
    public int getRequestNumber() {
        return requestNumber;
    }

    /**
     * Sets the value of the requestNumber property.
     * 
     */
    public void setRequestNumber(int value) {
        this.requestNumber = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the senderIdentity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderIdentity() {
        return senderIdentity;
    }

    /**
     * Sets the value of the senderIdentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderIdentity(String value) {
        this.senderIdentity = value;
    }

    /**
     * Gets the value of the serviceContextId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceContextId() {
        return serviceContextId;
    }

    /**
     * Sets the value of the serviceContextId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceContextId(String value) {
        this.serviceContextId = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserIdType }
     * 
     * 
     */
    public List<UserIdType> getUserId() {
        if (userId == null) {
            userId = new ArrayList<UserIdType>();
        }
        return this.userId;
    }

    /**
     * Gets the value of the operatorId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperatorId() {
        return operatorId;
    }

    /**
     * Sets the value of the operatorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperatorId(String value) {
        this.operatorId = value;
    }

    /**
     * Gets the value of the subsTimeZone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubsTimeZone() {
        return subsTimeZone;
    }

    /**
     * Sets the value of the subsTimeZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubsTimeZone(String value) {
        this.subsTimeZone = value;
    }

    /**
     * Gets the value of the locTimeZone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocTimeZone() {
        return locTimeZone;
    }

    /**
     * Sets the value of the locTimeZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocTimeZone(String value) {
        this.locTimeZone = value;
    }

    /**
     * Gets the value of the rollback property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRollback() {
        return rollback;
    }

    /**
     * Sets the value of the rollback property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRollback(Boolean value) {
        this.rollback = value;
    }

    /**
     * Gets the value of the code1 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCode1() {
        return code1;
    }

    /**
     * Sets the value of the code1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCode1(Integer value) {
        this.code1 = value;
    }

    /**
     * Gets the value of the code2 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCode2() {
        return code2;
    }

    /**
     * Sets the value of the code2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCode2(Integer value) {
        this.code2 = value;
    }

    /**
     * Gets the value of the code3 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCode3() {
        return code3;
    }

    /**
     * Sets the value of the code3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCode3(Integer value) {
        this.code3 = value;
    }

    /**
     * Gets the value of the purchaseCode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPurchaseCode() {
        return purchaseCode;
    }

    /**
     * Sets the value of the purchaseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPurchaseCode(Integer value) {
        this.purchaseCode = value;
    }

    /**
     * Gets the value of the subPurchaseCode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSubPurchaseCode() {
        return subPurchaseCode;
    }

    /**
     * Sets the value of the subPurchaseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSubPurchaseCode(Integer value) {
        this.subPurchaseCode = value;
    }

    /**
     * Gets the value of the additionalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalInfo() {
        return additionalInfo;
    }

    /**
     * Sets the value of the additionalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalInfo(String value) {
        this.additionalInfo = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtensionType }
     * 
     * 
     */
    public List<ExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<ExtensionType>();
        }
        return this.extension;
    }

}
