//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 08:40:35 AM CEST 
//


package com.telefonica.wsdl.unica.soap.charging.v1.interfaces;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.telefonica.schemas.unica.soap.charging.v1.ApplicationControlsListRequestType;
import com.telefonica.schemas.unica.soap.charging.v1.ExtensionType;
import com.telefonica.schemas.unica.soap.charging.v1.PriceType;
import com.telefonica.schemas.unica.soap.charging.v1.ThresholdsListRequestType;
import com.telefonica.schemas.unica.soap.common.v1.UserIdType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="requestId" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}RequestIdType"/>
 *         &lt;element name="timestamp" type="{http://www.telefonica.com/schemas/UNICA/SOAP/common/v1}TimestampType"/>
 *         &lt;element name="senderIdentity" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}SenderIdentityType"/>
 *         &lt;element name="userId" type="{http://www.telefonica.com/schemas/UNICA/SOAP/common/v1}UserIdType" maxOccurs="unbounded"/>
 *         &lt;element name="operatorId" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}OperatorIdType" minOccurs="0"/>
 *         &lt;element name="userLimit" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}PriceType" minOccurs="0"/>
 *         &lt;element name="thresholdsList" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}ThresholdsListRequestType" minOccurs="0"/>
 *         &lt;element name="applicationControlsList" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}ApplicationControlsListRequestType" minOccurs="0"/>
 *         &lt;element name="extension" type="{http://www.telefonica.com/schemas/UNICA/SOAP/charging/v1}ExtensionType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "requestId",
    "timestamp",
    "senderIdentity",
    "userId",
    "operatorId",
    "userLimit",
    "thresholdsList",
    "applicationControlsList",
    "extension"
})
@XmlRootElement(name = "setExpensesControlConfiguration")
public class SetExpensesControlConfiguration {

    @XmlElement(required = true)
    protected String requestId;
    @XmlElement(required = true)
    protected XMLGregorianCalendar timestamp;
    @XmlElement(required = true)
    protected String senderIdentity;
    @XmlElement(required = true)
    protected List<UserIdType> userId;
    protected String operatorId;
    protected PriceType userLimit;
    protected ThresholdsListRequestType thresholdsList;
    protected ApplicationControlsListRequestType applicationControlsList;
    protected List<ExtensionType> extension;

    /**
     * Gets the value of the requestId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * Sets the value of the requestId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestId(String value) {
        this.requestId = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the senderIdentity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderIdentity() {
        return senderIdentity;
    }

    /**
     * Sets the value of the senderIdentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderIdentity(String value) {
        this.senderIdentity = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserIdType }
     * 
     * 
     */
    public List<UserIdType> getUserId() {
        if (userId == null) {
            userId = new ArrayList<UserIdType>();
        }
        return this.userId;
    }

    /**
     * Gets the value of the operatorId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperatorId() {
        return operatorId;
    }

    /**
     * Sets the value of the operatorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperatorId(String value) {
        this.operatorId = value;
    }

    /**
     * Gets the value of the userLimit property.
     * 
     * @return
     *     possible object is
     *     {@link PriceType }
     *     
     */
    public PriceType getUserLimit() {
        return userLimit;
    }

    /**
     * Sets the value of the userLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceType }
     *     
     */
    public void setUserLimit(PriceType value) {
        this.userLimit = value;
    }

    /**
     * Gets the value of the thresholdsList property.
     * 
     * @return
     *     possible object is
     *     {@link ThresholdsListRequestType }
     *     
     */
    public ThresholdsListRequestType getThresholdsList() {
        return thresholdsList;
    }

    /**
     * Sets the value of the thresholdsList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ThresholdsListRequestType }
     *     
     */
    public void setThresholdsList(ThresholdsListRequestType value) {
        this.thresholdsList = value;
    }

    /**
     * Gets the value of the applicationControlsList property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationControlsListRequestType }
     *     
     */
    public ApplicationControlsListRequestType getApplicationControlsList() {
        return applicationControlsList;
    }

    /**
     * Sets the value of the applicationControlsList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationControlsListRequestType }
     *     
     */
    public void setApplicationControlsList(ApplicationControlsListRequestType value) {
        this.applicationControlsList = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtensionType }
     * 
     * 
     */
    public List<ExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<ExtensionType>();
        }
        return this.extension;
    }

}
