//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.03 at 04:59:10 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.telefonica.com/schemas/UNICA/REST/common/v2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package es.tid.neosdp.common.rest.v2;
