//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.05 at 02:12:15 PM CET 
//


package es.tid.neosdp.bluevia.schemas.location.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DistanceNotificationSubscriptionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DistanceNotificationSubscriptionsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="reference" type="{http://www.telefonica.com/schemas/UNICA/REST/common/v1}SimpleReferenceType"/>
 *         &lt;element name="requester" type="{http://www.telefonica.com/schemas/UNICA/REST/common/v1}UserIdType" minOccurs="0"/>
 *         &lt;element name="referenceAddress" type="{http://www.telefonica.com/schemas/UNICA/REST/common/v1}UserIdType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="monitoredAddress" type="{http://www.telefonica.com/schemas/UNICA/REST/common/v1}UserIdType" maxOccurs="unbounded"/>
 *         &lt;element name="distance" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="trackingAccuracy" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="criteria" type="{http://www.telefonica.com/schemas/UNICA/REST/location/v1/}DistanceCriteriaType"/>
 *         &lt;element name="checkInmediate" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="frequency" type="{http://www.telefonica.com/schemas/UNICA/REST/location/v1/}TimeMetricType"/>
 *         &lt;element name="duration" type="{http://www.telefonica.com/schemas/UNICA/REST/location/v1/}TimeMetricType" minOccurs="0"/>
 *         &lt;element name="count" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DistanceNotificationSubscriptionsType", propOrder = {
    "reference",
    "requester",
    "referenceAddress",
    "monitoredAddress",
    "distance",
    "trackingAccuracy",
    "criteria",
    "checkInmediate",
    "frequency",
    "duration",
    "count"
})
public class DistanceNotificationSubscriptionsType {

    @XmlElement(required = true)
    protected SimpleReferenceType reference;
    protected UserIdType requester;
    protected List<UserIdType> referenceAddress;
    @XmlElement(required = true)
    protected List<UserIdType> monitoredAddress;
    protected float distance;
    protected Float trackingAccuracy;
    @XmlElement(required = true)
    protected DistanceCriteriaType criteria;
    protected boolean checkInmediate;
    @XmlElement(required = true)
    protected TimeMetricType frequency;
    protected TimeMetricType duration;
    protected Integer count;

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleReferenceType }
     *     
     */
    public SimpleReferenceType getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleReferenceType }
     *     
     */
    public void setReference(SimpleReferenceType value) {
        this.reference = value;
    }

    /**
     * Gets the value of the requester property.
     * 
     * @return
     *     possible object is
     *     {@link UserIdType }
     *     
     */
    public UserIdType getRequester() {
        return requester;
    }

    /**
     * Sets the value of the requester property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserIdType }
     *     
     */
    public void setRequester(UserIdType value) {
        this.requester = value;
    }

    /**
     * Gets the value of the referenceAddress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the referenceAddress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReferenceAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserIdType }
     * 
     * 
     */
    public List<UserIdType> getReferenceAddress() {
        if (referenceAddress == null) {
            referenceAddress = new ArrayList<UserIdType>();
        }
        return this.referenceAddress;
    }

    /**
     * Gets the value of the monitoredAddress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the monitoredAddress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMonitoredAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserIdType }
     * 
     * 
     */
    public List<UserIdType> getMonitoredAddress() {
        if (monitoredAddress == null) {
            monitoredAddress = new ArrayList<UserIdType>();
        }
        return this.monitoredAddress;
    }

    /**
     * Gets the value of the distance property.
     * 
     */
    public float getDistance() {
        return distance;
    }

    /**
     * Sets the value of the distance property.
     * 
     */
    public void setDistance(float value) {
        this.distance = value;
    }

    /**
     * Gets the value of the trackingAccuracy property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getTrackingAccuracy() {
        return trackingAccuracy;
    }

    /**
     * Sets the value of the trackingAccuracy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setTrackingAccuracy(Float value) {
        this.trackingAccuracy = value;
    }

    /**
     * Gets the value of the criteria property.
     * 
     * @return
     *     possible object is
     *     {@link DistanceCriteriaType }
     *     
     */
    public DistanceCriteriaType getCriteria() {
        return criteria;
    }

    /**
     * Sets the value of the criteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistanceCriteriaType }
     *     
     */
    public void setCriteria(DistanceCriteriaType value) {
        this.criteria = value;
    }

    /**
     * Gets the value of the checkInmediate property.
     * 
     */
    public boolean isCheckInmediate() {
        return checkInmediate;
    }

    /**
     * Sets the value of the checkInmediate property.
     * 
     */
    public void setCheckInmediate(boolean value) {
        this.checkInmediate = value;
    }

    /**
     * Gets the value of the frequency property.
     * 
     * @return
     *     possible object is
     *     {@link TimeMetricType }
     *     
     */
    public TimeMetricType getFrequency() {
        return frequency;
    }

    /**
     * Sets the value of the frequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeMetricType }
     *     
     */
    public void setFrequency(TimeMetricType value) {
        this.frequency = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link TimeMetricType }
     *     
     */
    public TimeMetricType getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeMetricType }
     *     
     */
    public void setDuration(TimeMetricType value) {
        this.duration = value;
    }

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCount(Integer value) {
        this.count = value;
    }

}
