//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.05 at 02:12:15 PM CET 
//


package es.tid.neosdp.bluevia.schemas.location.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LocationNotificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LocationNotificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="reference" type="{http://www.telefonica.com/schemas/UNICA/REST/common/v1}SimpleReferenceType"/>
 *         &lt;element name="data" type="{http://www.telefonica.com/schemas/UNICA/REST/location/v1/}LocationDataType" maxOccurs="unbounded"/>
 *         &lt;element name="enteringLeavingCriteria" type="{http://www.telefonica.com/schemas/UNICA/REST/location/v1/}EnteringLeavingCriteriaType" minOccurs="0"/>
 *         &lt;element name="distanceCriteria" type="{http://www.telefonica.com/schemas/UNICA/REST/location/v1/}DistanceCriteriaType" minOccurs="0"/>
 *         &lt;element name="isFinalNotification" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LocationNotificationType", propOrder = {
    "reference",
    "data",
    "enteringLeavingCriteria",
    "distanceCriteria",
    "isFinalNotification"
})
public class LocationNotificationType {

    @XmlElement(required = true)
    protected SimpleReferenceType reference;
    @XmlElement(required = true)
    protected List<LocationDataType> data;
    protected EnteringLeavingCriteriaType enteringLeavingCriteria;
    protected DistanceCriteriaType distanceCriteria;
    protected Boolean isFinalNotification;

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleReferenceType }
     *     
     */
    public SimpleReferenceType getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleReferenceType }
     *     
     */
    public void setReference(SimpleReferenceType value) {
        this.reference = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the data property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocationDataType }
     * 
     * 
     */
    public List<LocationDataType> getData() {
        if (data == null) {
            data = new ArrayList<LocationDataType>();
        }
        return this.data;
    }

    /**
     * Gets the value of the enteringLeavingCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link EnteringLeavingCriteriaType }
     *     
     */
    public EnteringLeavingCriteriaType getEnteringLeavingCriteria() {
        return enteringLeavingCriteria;
    }

    /**
     * Sets the value of the enteringLeavingCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnteringLeavingCriteriaType }
     *     
     */
    public void setEnteringLeavingCriteria(EnteringLeavingCriteriaType value) {
        this.enteringLeavingCriteria = value;
    }

    /**
     * Gets the value of the distanceCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link DistanceCriteriaType }
     *     
     */
    public DistanceCriteriaType getDistanceCriteria() {
        return distanceCriteria;
    }

    /**
     * Sets the value of the distanceCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistanceCriteriaType }
     *     
     */
    public void setDistanceCriteria(DistanceCriteriaType value) {
        this.distanceCriteria = value;
    }

    /**
     * Gets the value of the isFinalNotification property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsFinalNotification() {
        return isFinalNotification;
    }

    /**
     * Sets the value of the isFinalNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsFinalNotification(Boolean value) {
        this.isFinalNotification = value;
    }

}
