//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.05 at 02:12:15 PM CET 
//


package es.tid.neosdp.bluevia.schemas.location.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LocationDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LocationDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="locatedParty" type="{http://www.telefonica.com/schemas/UNICA/REST/common/v1}UserIdType"/>
 *         &lt;element name="reportStatus" type="{http://www.telefonica.com/schemas/UNICA/REST/location/v1/}RetrievalStatusType"/>
 *         &lt;element name="currentLocation" type="{http://www.telefonica.com/schemas/UNICA/REST/location/v1/}LocationInfoType" minOccurs="0"/>
 *         &lt;element name="errorInformation" type="{http://www.telefonica.com/schemas/UNICA/REST/location/v1/}ServiceErrorType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LocationDataType", propOrder = {
    "locatedParty",
    "reportStatus",
    "currentLocation",
    "errorInformation"
})
public class LocationDataType {

    @XmlElement(required = true)
    protected UserIdType locatedParty;
    @XmlElement(required = true)
    protected RetrievalStatusType reportStatus;
    protected LocationInfoType currentLocation;
    protected ServiceErrorType errorInformation;

    /**
     * Gets the value of the locatedParty property.
     * 
     * @return
     *     possible object is
     *     {@link UserIdType }
     *     
     */
    public UserIdType getLocatedParty() {
        return locatedParty;
    }

    /**
     * Sets the value of the locatedParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserIdType }
     *     
     */
    public void setLocatedParty(UserIdType value) {
        this.locatedParty = value;
    }

    /**
     * Gets the value of the reportStatus property.
     * 
     * @return
     *     possible object is
     *     {@link RetrievalStatusType }
     *     
     */
    public RetrievalStatusType getReportStatus() {
        return reportStatus;
    }

    /**
     * Sets the value of the reportStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link RetrievalStatusType }
     *     
     */
    public void setReportStatus(RetrievalStatusType value) {
        this.reportStatus = value;
    }

    /**
     * Gets the value of the currentLocation property.
     * 
     * @return
     *     possible object is
     *     {@link LocationInfoType }
     *     
     */
    public LocationInfoType getCurrentLocation() {
        return currentLocation;
    }

    /**
     * Sets the value of the currentLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationInfoType }
     *     
     */
    public void setCurrentLocation(LocationInfoType value) {
        this.currentLocation = value;
    }

    /**
     * Gets the value of the errorInformation property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceErrorType }
     *     
     */
    public ServiceErrorType getErrorInformation() {
        return errorInformation;
    }

    /**
     * Sets the value of the errorInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceErrorType }
     *     
     */
    public void setErrorInformation(ServiceErrorType value) {
        this.errorInformation = value;
    }

}
