//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.05 at 02:12:15 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.telefonica.com/schemas/UNICA/REST/location/v1/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package es.tid.neosdp.bluevia.schemas.location.v1;
